name: Continuous Integration

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest  # Ou ubuntu-latest se preferir Linux

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          pip install --upgrade -r requirements.txt

          
  sast:
    needs: build  # SAST só será executado após o job de build
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Bandit
        run: pip install --upgrade bandit

      - name: Run Bandit SAST
        run: |
          bandit -r todo_project -f html -o sast_bandit.html || true

      - name: Upload Bandit SAST Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: sast_bandit.html

  dast:
    needs: build  # DAST será executado após o build
    runs-on: ubuntu-latest  # Usando Ubuntu para rodar Docker

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Docker
        run: |
          docker pull owasp/zap2docker-stable
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -r zap_report.html

      - name: Upload OWASP ZAP DAST Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html


  dependency-check:
    needs: build  # Verificação de dependência só será executada após o build
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download OWASP Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.0/dependency-check-7.4.0-release.zip --output dependency-check.zip

      - name: Unzip Dependency-Check
        run: |
          tar -xf dependency-check.zip -C .

      - name: Run Dependency-Check
        run: |
          .\dependency-check\bin\dependency-check.bat --project "My Project" --scan ./todo_project --out dependency-check-report.html

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html
