name: Continuous Integration

on:
  push:
    branches:
      develop


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name:
        run:
          bandit -r todo_project -o bandit_report.html
      - name: Run Project
        run: |
          python run.py