name: Continuous Integration

on:
  push:
    branches:
      develop


jobs:
  run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.
      - name: Install dependencies
        run: |
          pip install --upgrade Flask Flask-Bcrypt Flask-Login Flask-SQLAlchemy Flask-WTF WTForms Jinja2 Werkzeug
      - name: Bandit SAST
        run:
          bandit -r todo_project -f html -o sast_bandit.html
      - name: Run Tests
        run: |
          cd tests && pytest
      - name: Run Project
        run: |
          cd todo_project && python run.py